
name: CI Pipeline

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up C++
      uses: actions/setup-cpp@v1
      with:
        compiler: gcc

    - name: Configure CMake
      run: cmake -B build -S .

    - name: Build
      run: cmake --build build

    - name: Run Tests
      run: cd build && ctest --output-on-failure
